### PR TITLE
Reactive python 3.6 in gitsome

### LINKED ISSUE #105: Python 3.6: ply.yacc.YaccError: Unable to build parser
Running `python setup.py install` fails with `ply.yacc.YaccError: Unable to build parser`.

```
$ python setup.py install

running install
Building lexer and parser tables.
Traceback (most recent call last):
  File "setup.py", line 130, in <module>
    main()
  File "setup.py", line 123, in main
    setup(**skw)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 44, in run
    build_tables()
  File "setup.py", line 37, in build_tables
    outputdir='xonsh')
  File "/home/simon/src/gitsome/xonsh/parser.py", line 233, in __init__
    self.parser = yacc.yacc(**yacc_kwargs)
  File "/usr/lib/python3.6/site-packages/ply/yacc.py", line 3424, in yacc
    raise YaccError('Unable to build parser')
ply.yacc.YaccError: Unable to build parser
```

System info:
```
$ python 
Python 3.6.0 (default, Jan 16 2017, 12:12:55) 
[GCC 6.3.1 20170109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ply
>>> ply.__version__
'3.9'
```

---

**Edit by donnemartin**:  

`gitsome` does not currently support Python 3.6.  See this [comment](https://github.com/donnemartin/gitsome/issues/105#issuecomment-286078468) for more details and status.

### PR DESCRIPTION
**Pull request by szlin**
This PR  is trying to fix #105 and reactive python 3.6 in gitsome.

Since xonsh [has fixed the issue](https://github.com/xonsh/xonsh/pull/1717) in python 3.6, the gitsome should work fine with python 3.6.  I had some tests done on my side, please review on it.

Thanks.

### CODE REVIEW

**Comment by donnemartin** [comment]
Hi @szlin, I recall there were issues running in Python 3.6 because gitsome has a bundled version of xonsh, instead of listing it as a dependency.  I'm not seeing a change in this PR that addresses that?

**Comment by szlin** [comment]
@donnemartin Do you mind to remove embedded code copies with xonsh?  I am the gitsome package maintainer in Debian, and the xonsh has been removed according to [Debian policy 4.13](https://www.debian.org/doc/debian-policy/#convenience-copies-of-code), hence I had created a patch for it.
[Removal xonsh patch in Debian](https://anonscm.debian.org/git/collab-maint/gitsome.git/tree/debian/patches/0001-Remove-embedded-code-copies-xonsh.patch)

**Comment by donnemartin** [comment]
This is something I'm hoping to get fixed at some point with https://github.com/donnemartin/gitsome/issues/25, I recall at the time there were issues trying to unbundle xonsh.

It sounds like you've already done this, did you face any issues?

**Comment by szlin** [comment]
@donnemartin  I haven't seen any issues and received any bug reports so far since 2017-02-20. You may reference to following link: [gitsome in Debian](https://packages.debian.org/sid/main/gitsome)

**Comment by dbaio** [comment]
+1

It would be nice to unbundle `xonsh` and have a new release of `gitsome` as well.

Regards.

**Comment by ryukinix** [comment]
Looking for that getting merge for months! Great job guys :) Congrats. Waiting happily ~

**Comment by ryukinix** [comment]
Any news?

**Comment by donnemartin** [comment]
Hi everyone, I'm seeing issues with this, see https://github.com/donnemartin/gitsome/issues/105.

**Comment by szlin** [comment]
@donnemartin 
Sorry, I still don't get the point. The issue of #105 seems to be closed since upstream of xonsh had merged the patches.

The gitsome with my patches works fine for me, and got no bug report both in Debian [1] and Ubuntu [2] over past 10 months.

Could anyone provide the reproducible steps for python3.6 error in gitsome after applying my patches? I can have a look afterwards.

```
szlin@szlin-TW:/home/szlin/gitsome# python3 setup.py egg_info
running egg_info
creating gitsome.egg-info
writing gitsome.egg-info/PKG-INFO
writing dependency_links to gitsome.egg-info/dependency_links.txt
writing entry points to gitsome.egg-info/entry_points.txt
writing requirements to gitsome.egg-info/requires.txt
writing top-level names to gitsome.egg-info/top_level.txt
writing manifest file 'gitsome.egg-info/SOURCES.txt'
reading manifest file 'gitsome.egg-info/SOURCES.txt'
writing manifest file 'gitsome.egg-info/SOURCES.txt'
szlin@szlin-TW:/home/szlin/gitsome# python3 --version
Python 3.6.6+
```

[1] https://tracker.debian.org/pkg/gitsome
[2] https://launchpad.net/ubuntu/+source/gitsome

**Comment by iamareebjamal** [comment]
1.5 years since last release and a lot of people want 3.6 support. Contributors have sent a pull request. I request @donnemartin to please have a look, approve and merge it. If you see a problem with it, please convey it so that one the OP or someone else may address it. I understand that you might be busy with other things in your life, hence, you may think of adding some other maintainers on the project so it takes the load off your head, maybe?

People love this awesome tool but it is not moving forward

**Comment by donnemartin** [comment]
Hey all, sorry been really busy.  I'm starting to free up and plan to look into updating gitsome to support the latest Python versions.

**Comment by donnemartin** [comment]
Fixed with https://github.com/donnemartin/gitsome/pull/160, gitsome now support Python 3.7.

**Pull request closed without merging**
