### PR TITLE
readme: added `cd gitsome` in dev installation steps

### PR DESCRIPTION
**Pull request by notatestuser**

### CODE REVIEW

**Comment by donnemartin** [comment]
Thank you!

**Comment by notatestuser** [comment]
By the way, I wasn't sure if line 626 should also be changed to invoke `scripts/gitsome`. That seems to be required on Windows!

**Comment by donnemartin** [comment]
Hmm, I'm not sure it does.  I can run the current set of dev install commands on Windows 10 (with your `cd gitsome` change) with a proper pip install:

    $ git clone https://github.com/donnemartin/gitsome.git
    $ cd gitsome
    $ pip install -e .
    $ pip install -r requirements-dev.txt
    $ gitsome
    $ gh <command> [param] [options]

Perhaps it might be something in your environment?

**Comment by notatestuser** [comment]
Could be. I wasn't sure about it. Anyway thanks for the awesome tool!

**Pull request merged**
