### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### GitHub Corrected URLs 
Was | Now 
--- | --- 
https://github.com/mitsuhiko/click | https://github.com/pallets/click 

### HTTPS Corrected URLs 
Was | Now 
--- | --- 
http://img.shields.io/:license-apache-blue.svg | https://img.shields.io/:license-apache-blue.svg

### CODE REVIEW

**Comment by donnemartin** [comment]
@ReadmeCritic @dkhamsing I'm seeing the same issue as https://github.com/donnemartin/haxor-news/pull/39#issuecomment-213705071:

>Now
>https://img.shields.io/license-apache-blue.svg

I get this error page:

>I have nothing to offer for this request
>
>… but blood, toil, tears and sweat.
>
>Fortunately, the main page can offer rainbows instead!
>
>(You probably landed on this page because a link was broken, because someone mistyped its URL, or because of an irrelevant mistake. Don't worry, though: there is all of the rest of the Web to explore!)

**Comment by ReadmeCritic** [comment]
So sorry!! Fixing

**Comment by ReadmeCritic** [comment]
@donnemartin fixed!

**Comment by donnemartin** [comment]
Thank you!

**Pull request merged**
